name: API CI

# on: [push]
on:
  push:
    paths:
      - "testing-js/api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: testing-js/api

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: testing-js/api/package-lock.json
      - name: Install deps
        shell: bash
        run: npm ci
      - name: Run linter
        shell: bash
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: testing-js/api/package-lock.json
      - name: Install deps
        shell: bash
        run: npm ci
      - name: Run unit tests
        shell: bash
        run: npm run test
